### ISSUE TITLE
Is this package production ready?

### ISSUE THREAD

**Issue by cesarbess** [helpshift/HelpshiftX#1]
Hello all, i just stumbled upon this repository. My company uses Helpshift and we're currently locked on version 6.0, but right now we are refactoring the entire application from scratch, and we're moving all our dependencies to SPM. 

I'm wondering if we can use this Package over SPM and achieve the same results we were before with the official SDK? 

To put in another word, is this SDK the same as the one used here? https://github.com/helpshift/helpshift-ios-sdk-examples/
The fact that there's a X in the name made me confused :)

Thanks in advance

**Comment by jaydeep-helpshift** [comment]
Hey @cesarbess. The package included in the examples of https://github.com/helpshift/helpshift-ios-sdk-examples/ is a different product than this SPM package. We have two different Helpshift SDKs - [legacy SDK](https://developers.helpshift.com/ios/getting-started/) and[ SDK X](https://developers.helpshift.com/sdkx_ios/getting-started/). This package is for SDK X. Legacy SDK does not yet have SPM support. Hope that answers your question.

**Comment by cesarbess** [comment]
@jaydeep-helpshift Thank you, that helps. 

One last question: Do the legacy SDK matches the SDK X in terms of project configuration? Can we update using the same API keys and dashboard, or does it require something to be configured again?

Thanks in advance

**Comment by jaydeep-helpshift** [comment]
You can use the same dashboard and same API keys for SDK X. However, some of the SDK APIs have changed in SDK X. You can find more details about the differences, and also information on how to migrate from legacy to SDK X [here](https://developers.helpshift.com/sdkx_ios/migration-guide/).

**Comment by cesarbess** [comment]
Thank you for the information.
