### ISSUE TITLE
Consider making global constants extern instead of static

### ISSUE THREAD

**Issue by rsnively** [helpshift/HelpshiftX#3]
The global constants declared in `Helpshift.h` and `HelpshiftDelegate.h` are all declared as `static`.

For our particular use case, we access these constants across an FFI boundary. Since static global variables are only accessible in files that include the header directly, it is difficult for us to access these constants.

Using `extern` (or more realistically `FOUNDATION_EXPORT`) instead of static would solve our issue, and seems to be the generally preferred method of exposing constants in a framework, as other issues can arise when declaring constants as static in a header (https://stackoverflow.com/a/539191/12092629).

**Comment by jaydeep-helpshift** [comment]
@rsnively Thanks for the feedback. We will be fixing this issue in the upcoming SDK X release. In the meantime, as a workaround, can you try using the values of the constants directly in your code? The values can be found inside the header files included in the framework.

**Comment by jaydeep-helpshift** [comment]
This has been fixed with SDK X 10.3.0. Closing the ticket.
